name: ifafu
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  shared_preferences: ^2.2.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  carousel_slider: ^4.2.1
  flutter_bloc: ^8.1.3
  infinite_scroll_pagination: ^4.0.0
  photo_view: ^0.14.0
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  wechat_assets_picker: ^8.7.1
  image_cropper: ^5.0.0
  pull_to_refresh: ^2.0.0
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.3
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/image/defaultAvatar.png
    - assets/image/empty.png
    - assets/image/location.svg
    - assets/image/logo_jw.png
    - assets/image/logo_fafu.png
    - assets/image/qa.png
    - assets/image/bot.jpg

  fonts:
    - family: DingTalk
      fonts:
        - asset: assets/font/DingTalk.ttf